name: Run Crypto Bot
on: 
  workflow_dispatch:  # Ручной запуск
  push:               # Автозапуск при изменениях
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev libffi-dev
        
    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Telegram Bot
      env:
        TOKEN: ${{ secrets.TOKEN }}
        ADMIN_ID: ${{ secrets.ADMIN_ID }}
        ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
      run: python crypto_bot.py
